#ifndef RECORDER_BUILDER_H
#define RECORDER_BUILDER_H

/* Generated by flatcc 0.6.2 FlatBuffers schema compiler for C by dvide.com */

#ifndef RECORDER_READER_H
#include "recorder_reader.h"
#endif
#ifndef FLATBUFFERS_COMMON_BUILDER_H
#include "flatbuffers_common_builder.h"
#endif
#include "flatcc/flatcc_prologue.h"
#ifndef flatbuffers_identifier
#define flatbuffers_identifier 0
#endif
#ifndef flatbuffers_extension
#define flatbuffers_extension "bin"
#endif

static const flatbuffers_voffset_t __journal_Entry_required[] = { 0 };
typedef flatbuffers_ref_t journal_Entry_ref_t;
static journal_Entry_ref_t journal_Entry_clone(flatbuffers_builder_t *B, journal_Entry_table_t t);
__flatbuffers_build_table(flatbuffers_, journal_Entry, 13)

static const flatbuffers_voffset_t __journal_Chunk_required[] = { 0 };
typedef flatbuffers_ref_t journal_Chunk_ref_t;
static journal_Chunk_ref_t journal_Chunk_clone(flatbuffers_builder_t *B, journal_Chunk_table_t t);
__flatbuffers_build_table(flatbuffers_, journal_Chunk, 1)

#define __journal_Entry_formal_args ,\
  uint64_t v0, uint64_t v1, uint8_t v2, flatbuffers_string_ref_t v3,\
  flatbuffers_string_ref_t v4, flatbuffers_string_ref_t v5, uint32_t v6, uint32_t v7,\
  uint32_t v8, flatbuffers_string_ref_t v9, flatbuffers_string_ref_t v10, flatbuffers_string_ref_t v11, uint16_t v12
#define __journal_Entry_call_args ,\
  v0, v1, v2, v3,\
  v4, v5, v6, v7,\
  v8, v9, v10, v11, v12
static inline journal_Entry_ref_t journal_Entry_create(flatbuffers_builder_t *B __journal_Entry_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, journal_Entry, journal_Entry_file_identifier, journal_Entry_type_identifier)

#define __journal_Chunk_formal_args , journal_Entry_vec_ref_t v0
#define __journal_Chunk_call_args , v0
static inline journal_Chunk_ref_t journal_Chunk_create(flatbuffers_builder_t *B __journal_Chunk_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, journal_Chunk, journal_Chunk_file_identifier, journal_Chunk_type_identifier)

__flatbuffers_build_scalar_field(0, flatbuffers_, journal_Entry_realtime_ts, flatbuffers_uint64, uint64_t, 8, 8, UINT64_C(0), journal_Entry)
__flatbuffers_build_scalar_field(1, flatbuffers_, journal_Entry_monotonic_ts, flatbuffers_uint64, uint64_t, 8, 8, UINT64_C(0), journal_Entry)
__flatbuffers_build_scalar_field(2, flatbuffers_, journal_Entry_priority, flatbuffers_uint8, uint8_t, 1, 1, UINT8_C(0), journal_Entry)
__flatbuffers_build_string_field(3, flatbuffers_, journal_Entry_message, journal_Entry)
__flatbuffers_build_string_field(4, flatbuffers_, journal_Entry_message_id, journal_Entry)
__flatbuffers_build_string_field(5, flatbuffers_, journal_Entry_unit, journal_Entry)
__flatbuffers_build_scalar_field(6, flatbuffers_, journal_Entry_pid, flatbuffers_uint32, uint32_t, 4, 4, UINT32_C(0), journal_Entry)
__flatbuffers_build_scalar_field(7, flatbuffers_, journal_Entry_uid, flatbuffers_uint32, uint32_t, 4, 4, UINT32_C(0), journal_Entry)
__flatbuffers_build_scalar_field(8, flatbuffers_, journal_Entry_gid, flatbuffers_uint32, uint32_t, 4, 4, UINT32_C(0), journal_Entry)
__flatbuffers_build_string_field(9, flatbuffers_, journal_Entry_hostname, journal_Entry)
__flatbuffers_build_string_field(10, flatbuffers_, journal_Entry_comm, journal_Entry)
__flatbuffers_build_string_field(11, flatbuffers_, journal_Entry_exe, journal_Entry)
__flatbuffers_build_scalar_field(12, flatbuffers_, journal_Entry_errno, flatbuffers_uint16, uint16_t, 2, 2, UINT16_C(0), journal_Entry)

static inline journal_Entry_ref_t journal_Entry_create(flatbuffers_builder_t *B __journal_Entry_formal_args)
{
    if (journal_Entry_start(B)
        || journal_Entry_realtime_ts_add(B, v0)
        || journal_Entry_monotonic_ts_add(B, v1)
        || journal_Entry_message_add(B, v3)
        || journal_Entry_message_id_add(B, v4)
        || journal_Entry_unit_add(B, v5)
        || journal_Entry_pid_add(B, v6)
        || journal_Entry_uid_add(B, v7)
        || journal_Entry_gid_add(B, v8)
        || journal_Entry_hostname_add(B, v9)
        || journal_Entry_comm_add(B, v10)
        || journal_Entry_exe_add(B, v11)
        || journal_Entry_errno_add(B, v12)
        || journal_Entry_priority_add(B, v2)) {
        return 0;
    }
    return journal_Entry_end(B);
}

static journal_Entry_ref_t journal_Entry_clone(flatbuffers_builder_t *B, journal_Entry_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (journal_Entry_start(B)
        || journal_Entry_realtime_ts_pick(B, t)
        || journal_Entry_monotonic_ts_pick(B, t)
        || journal_Entry_message_pick(B, t)
        || journal_Entry_message_id_pick(B, t)
        || journal_Entry_unit_pick(B, t)
        || journal_Entry_pid_pick(B, t)
        || journal_Entry_uid_pick(B, t)
        || journal_Entry_gid_pick(B, t)
        || journal_Entry_hostname_pick(B, t)
        || journal_Entry_comm_pick(B, t)
        || journal_Entry_exe_pick(B, t)
        || journal_Entry_errno_pick(B, t)
        || journal_Entry_priority_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, journal_Entry_end(B));
}

__flatbuffers_build_table_vector_field(0, flatbuffers_, journal_Chunk_entries, journal_Entry, journal_Chunk)

static inline journal_Chunk_ref_t journal_Chunk_create(flatbuffers_builder_t *B __journal_Chunk_formal_args)
{
    if (journal_Chunk_start(B)
        || journal_Chunk_entries_add(B, v0)) {
        return 0;
    }
    return journal_Chunk_end(B);
}

static journal_Chunk_ref_t journal_Chunk_clone(flatbuffers_builder_t *B, journal_Chunk_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (journal_Chunk_start(B)
        || journal_Chunk_entries_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, journal_Chunk_end(B));
}

#include "flatcc/flatcc_epilogue.h"
#endif /* RECORDER_BUILDER_H */
