#ifndef RECORDER_READER_H
#define RECORDER_READER_H

/* Generated by flatcc 0.6.2 FlatBuffers schema compiler for C by dvide.com */

#ifndef FLATBUFFERS_COMMON_READER_H
#include "flatbuffers_common_reader.h"
#endif
#include "flatcc/flatcc_flatbuffers.h"
#ifndef __alignas_is_defined
#include <stdalign.h>
#endif
#include "flatcc/flatcc_prologue.h"
#ifndef flatbuffers_identifier
#define flatbuffers_identifier 0
#endif
#ifndef flatbuffers_extension
#define flatbuffers_extension "bin"
#endif


typedef const struct journal_Entry_table *journal_Entry_table_t;
typedef struct journal_Entry_table *journal_Entry_mutable_table_t;
typedef const flatbuffers_uoffset_t *journal_Entry_vec_t;
typedef flatbuffers_uoffset_t *journal_Entry_mutable_vec_t;
typedef const struct journal_Chunk_table *journal_Chunk_table_t;
typedef struct journal_Chunk_table *journal_Chunk_mutable_table_t;
typedef const flatbuffers_uoffset_t *journal_Chunk_vec_t;
typedef flatbuffers_uoffset_t *journal_Chunk_mutable_vec_t;
#ifndef journal_Entry_file_identifier
#define journal_Entry_file_identifier 0
#endif
/* deprecated, use journal_Entry_file_identifier */
#ifndef journal_Entry_identifier
#define journal_Entry_identifier 0
#endif
#define journal_Entry_type_hash ((flatbuffers_thash_t)0xc9603ca)
#define journal_Entry_type_identifier "\xca\x03\x96\x0c"
#ifndef journal_Entry_file_extension
#define journal_Entry_file_extension "bin"
#endif
#ifndef journal_Chunk_file_identifier
#define journal_Chunk_file_identifier 0
#endif
/* deprecated, use journal_Chunk_file_identifier */
#ifndef journal_Chunk_identifier
#define journal_Chunk_identifier 0
#endif
#define journal_Chunk_type_hash ((flatbuffers_thash_t)0x56fdec27)
#define journal_Chunk_type_identifier "\x27\xec\xfd\x56"
#ifndef journal_Chunk_file_extension
#define journal_Chunk_file_extension "bin"
#endif



struct journal_Entry_table { uint8_t unused__; };

static inline size_t journal_Entry_vec_len(journal_Entry_vec_t vec)
__flatbuffers_vec_len(vec)
static inline journal_Entry_table_t journal_Entry_vec_at(journal_Entry_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(journal_Entry_table_t, vec, i, 0)
__flatbuffers_table_as_root(journal_Entry)

__flatbuffers_define_scalar_field(0, journal_Entry, realtime_ts, flatbuffers_uint64, uint64_t, UINT64_C(0))
__flatbuffers_define_scalar_field(1, journal_Entry, monotonic_ts, flatbuffers_uint64, uint64_t, UINT64_C(0))
__flatbuffers_define_scalar_field(2, journal_Entry, priority, flatbuffers_uint8, uint8_t, UINT8_C(0))
__flatbuffers_define_string_field(3, journal_Entry, message, 0)
__flatbuffers_define_string_field(4, journal_Entry, message_id, 0)
__flatbuffers_define_string_field(5, journal_Entry, unit, 0)
__flatbuffers_define_scalar_field(6, journal_Entry, pid, flatbuffers_uint32, uint32_t, UINT32_C(0))
__flatbuffers_define_scalar_field(7, journal_Entry, uid, flatbuffers_uint32, uint32_t, UINT32_C(0))
__flatbuffers_define_scalar_field(8, journal_Entry, gid, flatbuffers_uint32, uint32_t, UINT32_C(0))
__flatbuffers_define_string_field(9, journal_Entry, hostname, 0)
__flatbuffers_define_string_field(10, journal_Entry, comm, 0)
__flatbuffers_define_string_field(11, journal_Entry, exe, 0)
__flatbuffers_define_scalar_field(12, journal_Entry, errno, flatbuffers_uint16, uint16_t, UINT16_C(0))

struct journal_Chunk_table { uint8_t unused__; };

static inline size_t journal_Chunk_vec_len(journal_Chunk_vec_t vec)
__flatbuffers_vec_len(vec)
static inline journal_Chunk_table_t journal_Chunk_vec_at(journal_Chunk_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(journal_Chunk_table_t, vec, i, 0)
__flatbuffers_table_as_root(journal_Chunk)

__flatbuffers_define_vector_field(0, journal_Chunk, entries, journal_Entry_vec_t, 0)


#include "flatcc/flatcc_epilogue.h"
#endif /* RECORDER_READER_H */
