namespace journal;

table Field {
  name:string;
  value:[ubyte];
}

table CompactEntry {
  realtime_ts:ulong;
  monotonic_ts:ulong;
  priority:ubyte;
  message:string;
  pid:uint;
  unit:string;
}

table FullEntry {
  // timestamps
  realtime_ts:ulong;
  monotonic_ts:ulong;

  // core log fields
  priority:ubyte;
  message:string;
  fields:[Field];
  message_id:string;
  unit:string;

  // identity
  pid:uint;
  uid:uint;
  gid:uint;

  // optional strings
  hostname:string;
  comm:string;
  exe:string;

  // optional structured field
  errno:ushort = 0;
}

table Chunk {
  entries:[FullEntry];
}

table DefaultChunk {
  entries:[CompactEntry];
}

root_type Chunk;
